[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

# Proxying to backend service
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 